version: 0.0
os: linux

files:
  - source:  /
    destination: /home/ubuntu/spring-github-action
    overwrite: yes
permissions:
  - object: /home/ubuntu/spring-github-action
    owner: ubuntu
    group: ubuntu
    mode: -R 777
hooks:
  AfterInstall:
    - location: scripts/stop.sh
      timeout: 60
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 60
