spring:
  config:
    activate:
      on-profile: "swagger"

springdoc:
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    operations-sorter: alpha

basic-auth:
  username: ${BASIC_AUTH_USERNAME:default}
  password: ${BASIC_AUTH_PASSWORD:default}
